# Generated by Django 5.2.8 on 2025-12-03 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated_at',
        ),
    ]
