# Generated by Django 5.2.8 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_is_deleted_remove_message_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
