# Generated by Django 4.2.10 on 2026-07-08 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0039_alter_businessprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicequote',
            name='preferred_date',
        ),
        migrations.RemoveField(
            model_name='servicequote',
            name='preferred_time',
        ),
    ]
