# Generated by Django 5.2.8 on 2025-11-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('category', models.CharField(choices=[('General', 'General'), ('Report', 'Report'), ('Support', 'Support')], default='General', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Replied', 'Replied'), ('Read', 'Read')], default='New', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
