# Generated by Django 4.2.10 on 2026-08-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='apple_original_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='apple_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('apple', 'Apple'), ('manual', 'Manual')], default='stripe', max_length=20),
        ),
    ]
