# Generated by Django 4.2.10 on 2026-08-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_subscription_apple_original_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='apple_product_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
