# Generated by Django 4.2.10 on 2026-07-04 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0007_alter_bookingrequest_booking_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_service_bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
