# Generated by Django 4.2.10 on 2026-07-04 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landscapers', '0039_alter_businessprofile_latitude_and_more'),
        ('bookings', '0008_alter_servicebooking_landscaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicebooking',
            name='landscaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='landscapers.businessprofile'),
        ),
    ]
